name: SENDTokens
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
      - run: foo=$(cat tokens/input.json | sed 's/"/\\"/g') && echo "{\"event_type\":\"update-tokens\",\"client_payload\":{\"tokens\":\"$foo\"}}" > sendThis.json
      - run: sudo apt update && sudo apt install curl -y
      - run: curl -X POST https://api.github.com/repos/tom-sosedow/foo-projekt/dispatches -d @sendThis.json -H "Accept:application/vnd.github.everest-preview+json" -H "Authorization:token ${{ secrets.AUTH_TOKEN }}"
    

