name: SENDTokens
on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          data: ${{ toJSON(github.event) }}
          webhook_url: "https://api.github.com/repos/tom-sosedow/foo-projekt/dispatches"
          options: '-H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}"'

