name: SENDTokens
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
      - run: cat tokens/input.json
      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          data: tokens/input.json
          webhook_url: "https://api.github.com/repos/tom-sosedow/foo-projekt/dispatches"
          options: '-H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}"'

