name: SENDTokens
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
      - name: set up env var
        run: echo "foo=$(cat tokens/input.json | sed 's/"/\\"/g')" >> $GITHUB_ENV
      - run: echo "{\"event_type\":\"update-tokens\",\"client_payload\":{\"tokens\":\"${{env.foo}}\"}}" > sendThis.json
      - run: cat sendThis.json
      - run: sudo apt update && sudo apt install curl -y
      - run: curl -X POST https://api.github.com/repos/tom-sosedow/foo-projekt/dispatches -d @sendThis.json -H "Accept:application/vnd.github.everest-preview+json" -H "Authorization:token ${{ secrets.AUTH_TOKEN }}"
      #- name: Webhook
      #  uses: zzzze/webhook-trigger@master
      #  with:
      #    data: \@sendThis.json
      #    webhook_url: "https://api.github.com/repos/tom-sosedow/foo-projekt/dispatches"
      #    options: '-H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.AUTH_TOKEN }}"'

